api_platform:
  title: Hello API Platform
  version: 1.0.0
  formats:
    json: [ 'application/json' ]
  docs_formats:
    json: [ 'application/json' ]
    html: [ 'text/html' ]
  error_formats:
    json: [ 'application/json' ]
  defaults:
    stateless: true
    cache_headers:
      vary: [ 'Content-Type', 'Authorization', 'Origin' ]
    extra_properties:
      standard_put: true
      rfc_7807_compliant_errors: true
    pagination_enabled: false
  keep_legacy_inflector: false
  use_symfony_listeners: true

when@dist:
  api_platform:
    enable_docs: false
    enable_entrypoint: false
    enable_swagger_ui: false
