name: supervisord-monitor

services:
  supervisord-monitor-app:
    container_name: supervisord-monitor-app
    user: app
    build:
      args:
        - BUILD_TYPE=dev
        - PUID=1000
        - PGID=1000
        - DEV_XDEBUG_AUTOSTART=trigger
        - PHP_IDE_CONFIG=serverName=Docker
    environment:
      - PHP_IDE_CONFIG=serverName=Docker
      - API_HOST=localhost
      - JWT_PASSPHRASE=73e14354e3850602ceb82c34c17c56e4aee66dbc9b0bda91652e2f57cb2200b3
    volumes:
      - ./:/var/www/supervisord-monitor:cached
      - ./docker/nginx/dev/supervisord-monitor.local.crt:/etc/nginx/ssl/supervisord-monitor.local.crt
      - ./docker/nginx/dev/supervisord-monitor.local.key:/etc/nginx/ssl/supervisord-monitor.local.key
      - ./tests/Functional/resources/supervisord_servers.yaml:/var/www/supervisord-monitor/config/app/supervisord_servers.yaml
      - ./docker/supervisor/supervisord-dev.conf:/etc/supervisord.conf
    ports:
      - "8080:8080" # Dev mode(backend) - Deprecated
      - "5173:5173" # Dev mode(frontend) - Deprecated
      - "10011:8080" # Prod mode emulation - Deprecated
      - "80:8080" # Dev mode(for cookies setup)
      - "443:4430" # Dev mode(for cookies setup)
    networks:
      - supervisord_monitor_network

  supervisord-monitor-test-server:
    user: app
    build:
      context: tests/Functional/resources
      args:
        - UID=1000
        - GID=1000
    volumes:
      - ./tests/Functional/resources/:/var/www/supervisord-monitor:cached
    networks:
      - supervisord_monitor_network
    deploy:
      mode: replicated
      replicas: 6

networks:
  supervisord_monitor_network:
    name: supervisord_monitor_network
    external: true
