version: "3.8"

name: supervisord-monitor

services:
  supervisord-monitor-app:
    container_name: supervisord-monitor-app
    user: app
    build:
      context: ./../../
      dockerfile: ./config/docker/Dockerfile
      args:
        - WEB_PORT=${WEB_PORT}
        - BUILD_TYPE=dev
        - PUID=${PUID}
        - PGID=${PGID}
        - SUPERVISORS_SERVERS=${SUPERVISORS_SERVERS}
        - DEV_XDEBUG_AUTOSTART=${DEV_XDEBUG_AUTOSTART}
    volumes:
      - ./../../:/var/www/supervisor-monitor:cached
    ports:
      - ${WEB_PORT}:${WEB_PORT}
      - "5173:5173" # Dev mode
    networks:
      - supervisord_monitor_network

  supervisord-monitor-test-server:
    user: app
    build:
      context: ./../../tests/Functional/resources/
      args:
        - UID=${PUID}
        - GID=${PGID}
    volumes:
      - ./../../tests/Functional/resources/:/var/www/supervisor-monitor:cached
    networks:
      - supervisord_monitor_network
    deploy:
      mode: replicated
      replicas: 6

networks:
  supervisord_monitor_network:
    name: ${EXTERNAL_NETWORK_NAME}
    external: true
