version: "3.8"

name: supervisord-monitor

services:
  supervisord-monitor-app:
    container_name: supervisord-monitor-app
    user: app
    build:
      context: ./../../
      dockerfile: ./config/docker/Dockerfile
      args:
        - BUILD_TYPE=dev
        - PUID=${PUID}
        - PGID=${PGID}
        - DEV_XDEBUG_AUTOSTART=${DEV_XDEBUG_AUTOSTART}
    environment:
        - SUPERVISORS_SERVERS=${SUPERVISORS_SERVERS}
        - API_HOST=${API_HOST}
        - JWT_PASSPHRASE=${JWT_PASSPHRASE}
        - APP_CREDENTIALS=${APP_CREDENTIALS}
    volumes:
      - ./../../:/var/www/supervisor-monitor:cached
      - ./../../config/docker/nginx/dev/supervisord-monitor.local.crt:/etc/nginx/ssl/supervisord-monitor.local.crt
      - ./../../config/docker/nginx/dev/supervisord-monitor.local.key:/etc/nginx/ssl/supervisord-monitor.local.key
    ports:
      - "8080:8080" # Dev mode(backend) - Deprecated
      - "5173:5173" # Dev mode(frontend) - Deprecated
      - "10011:8080" # Prod mode emulation - Deprecated
      - "80:8080" # Dev mode(for cookies setup)
      - "443:4430" # Dev mode(for cookies setup)
    networks:
      - supervisord_monitor_network

  supervisord-monitor-test-server:
    user: app
    build:
      context: ./../../tests/Functional/resources/
      args:
        - UID=${PUID}
        - GID=${PGID}
    volumes:
      - ./../../tests/Functional/resources/:/var/www/supervisor-monitor:cached
    networks:
      - supervisord_monitor_network
    deploy:
      mode: replicated
      replicas: 6

networks:
  supervisord_monitor_network:
    name: ${EXTERNAL_NETWORK_NAME}
    external: true
