parameters:
  supervisordServers: '%env(supervisordServers:SUPERVISORS_SERVERS)%'
  appCredentials: '%env(appCredentials:APP_CREDENTIALS)%'
  collectIntervalInMicroseconds: '%env(int:COLLECT_INTERVAL_IN_MICROSECONDS)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/'
    exclude:
      - '../src/Kernel.php'
      - '../src/{DTO,Enum,Exception}'
      - '../src/Service/SupervisorApiClient.php'
