parameters:
  supervisors_servers: [ { "ip": "supervisord-monitor-supervisord-monitor-supervisord-monitor-test-server-1","port": 9555,"name": "default","username": "default","password": "default" } ]
