# APP_CREDENTIALS Env var fallback. Can be used with a large number of users.
# If no APP_CREDENTIALS environment variable has been set this configuration will be taken.
app_credentials:
  - username: admin
    password: admin
    roles:
      - ROLE_MANAGER

  - username: guest
    password: guest
    roles: [ ]
