name: Build and Push Docker Image

env:
  IMAGE_WITH_TAG: ${{ format('{0}:{1}', secrets.CI_REGISTRY_IMAGE, github.run_number) }}
  LATEST_IMAGE: ${{ format('{0}:latest', secrets.CI_REGISTRY_IMAGE) }}

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create .env file for frontend
        run: echo "VITE_API_URL='/api'" > .env
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.CI_REGISTRY }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: Build and Push Docker Image
        run: docker buildx build -f config/docker/Dockerfile -t $IMAGE_WITH_TAG --load .
      - name: Push Docker Image
        run: docker push $IMAGE_WITH_TAG
      - name: Set as latest
        run: docker tag $IMAGE_WITH_TAG $LATEST_IMAGE
      - name: Push Docker Image
        run: docker push $LATEST_IMAGE
